repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.3.245 # change to tag or sha
    hooks:
      - id: checkov
        args: [--skip-check, 'CKV_K8S_21, CKV2_GHA_1']
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_tfsec
      - id: terraform_docs
      - id: terraform_fmt
        args:
          - --args=-diff
      - id: terraform_tflint
        args:
          - --args=--module
      - id: terraform_validate
