repos:
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.3.114 # change to tag or sha
    hooks:
      - id: checkov
        args: [--skip-check, 'CKV_K8S_21']
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_tfsec
      - id: terraform_docs
      - id: terraform_fmt
        args:
          - --args=-diff
      - id: terraform_tflint
        args:
          - --args=--module
      - id: terraform_validate
