repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.2
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.80.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
      - id: terraform_tflint
        args:
          - --args=--module
      - id: terraform_validate
  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.1
    hooks:
      - id: tfsec
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "--output-file", "README.md", "./modules/virtual-machine"]
      - id: terraform-docs-go
        args: ["markdown", "--output-file", "README.md", "./modules/kubernetes-nodeport"]
      - id: terraform-docs-go
        args: ["markdown", "--output-file", "README.md", "./modules/kubernetes-clusterip"]
