---
- name: main
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: plan
      community.general.terraform:
        project_path: "./tf"
        plan_file: "./tf/tfplan"
        lock: true
        state: planned

    - name: apply
      community.general.terraform:
        project_path: "./tf"
        lock: true
        state: present

    - name: destroy
      community.general.terraform:
        project_path: "./tf"
        lock: true
        state: absent
