#cloud-config
##...
package_update: true
disable_root: false
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
users:
  ${USER_NAME}:
    groups:
      - "wheel"
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: ${USER_PASSWORD_HASH}
    lock_passwd: false
    shell: /bin/bash
    ssh_authorized_keys:
      - ${USER_PUBLIC_KEY_PATH}
##...
